export const environment = {
  production: true,
  registerUrl: "http://localhost:3001/api/auth/register/",
  usersUrl: "http://localhost:3001/api/users/",
  citiesUrl: "http://localhost:3001/api/cities/",
  loginUrl: "http://localhost:3001/api/auth/login/",
  categoryUrl: "http://localhost:3001/api/products/categories/",
  productsUrl: "http://localhost:3001/api/products/",
  searchProductsUrl: "http://localhost:3001/api/products/search/",
  productsCountsUrl: "http://localhost:3001/api/products/count/",
  productImagesUrl: "http://localhost:3001/api/products/images/",
  productsByCategoryUrl: "http://localhost:3001/api/products/by-category/",
  ordersUrl: "http://localhost:3001/api/orders/",
  cardsUrl: "http://localhost:3001/api/cards/",
  cardsProductsUrl: "http://localhost:3001/api/cards-products/",
  searchCardsProductsUrl: "http://localhost:3001/api/cards-products/search/",
};
